# Generated by Django 5.0.7 on 2024-07-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=11, unique=True)),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel')], max_length=8)),
                ('ano_lancamento', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel')], max_length=8)),
                ('total_litros', models.IntegerField(max_length=2)),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_abastecimento', models.DateField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.veiculo')),
            ],
        ),
    ]
