# Generated by Django 5.0.7 on 2024-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='total_litros',
            field=models.IntegerField(),
        ),
    ]
