# Generated by Django 5.0.7 on 2024-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_alter_abastecimento_total_litros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano_lancamento',
            field=models.IntegerField(),
        ),
    ]
