# Generated by Django 5.0.7 on 2024-07-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_alter_veiculo_ano_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data_abastecimento',
            field=models.DateTimeField(),
        ),
    ]
